### ISSUE TITLE
Consider adding documents as a PR for feedback

### ISSUE THREAD

**Issue by xuorig** [LiUGraphQL/LinGBM#1]
Hey 👋, just stumbled on this, very cool idea and project. Maybe you could consider opening a PR with your initial assumptions / documents for easier feedback. It's hard to comment on a wiki. If not, how would you like to receive feedback?

Thanks!

**Comment by hartig** [comment]
Hi Marc-André, thanks a lot for your interest! I can see that commenting on the wiki is difficult. Based on your suggestion, I have copied a skeleton of the document with the choke points into the repo itself. Next, I have created separate PRs, one for each of the choke points in the document, and I have extended the wiki page with links to these PRs. We are looking forward to your comments on the choke points.

Please close this issue if you agree that providing feedback is easier now.

**Comment by xuorig** [comment]
Thanks @hartig! I will read this more carefully tomorrow and provide some thoughts. Again, very cool stuff!
