### ISSUE TITLE
Missing placeholder for qt9 in documentation

### ISSUE THREAD

**Issue by ArenasGuerreroJulian** [LiUGraphQL/LinGBM#120]
Hi,

I think that template qt9 is missing a placeholder in the [documentation](https://github.com/LiUGraphQL/LinGBM/wiki/Query-Templates-of-the-Benchmark#qt9). Currently only one is specified (Placeholders: $universityID).

Julián

**Comment by hartig** [comment]
Hi Julián, you are right, the information about the second placeholder of QT9 is indeed missing in the documentation in the wiki. Thanks for spotting this issue and letting us know!

@chengsijin0817 can you please add this information to the wiki.

**Comment by chengsijin0817** [comment]
Hi Julián @ArenasGuerreroJulian, I have updated the query templates docs. Please feel free to let me know if you find any other information is missing.
