### ISSUE TITLE
Update LinGBM.wiki

### ISSUE THREAD

**Issue by chengsijin0817** [LiUGraphQL/LinGBM#28]
- [x] GraphQL schema
- [x] query templates
- [x] Performance metrics
- [x] Create sidebar
- [x] restructrure the directory of Git repo

**Comment by chengsijin0817** [comment]
Hi, @hartig, I complete updating the wiki pages and restructure the directory of the Git repository.
Please check it.

**Comment by hartig** [comment]
Thanks Sijin!
