### ISSUE TITLE
'offerWhereInput' issues

### ISSUE THREAD

**Issue by chengsijin0817** [LiUGraphQL/LinGBM#29]

**Comment by ljukas** [comment]
So the discussion we had was that our OfferWhereInput could closer resemble Hasuras as seen here: `https://docs.hasura.io/1.0/graphql/manual/api-reference/graphql-api/query.html#whereexp` @chengsijin0817  also said we maybe should favoritize a existing solution. I think however since this is just an input it might not matter that much. 

Hasuras input implementation closely resembles a sql-query in itself and is a pretty natural way of writing the input.

How do you think we should proceed? @chengsijin0817  @hartig

**Comment by ljukas** [comment]
After some research into how hasuras WhereInput works, it is actually very similar to our original approach, it just makes some assumptions on the query sent to not be weirdly formed.

**Comment by ljukas** [comment]
So, a short question:

input VendorFieldInput
{
  nr: ID
  comment: [StringMatching]
  publishDate: [DateMatching] 
}


This input, why is comment and publishDate arrays? Shouldn't that functionallity be handled  by the "AND" in the root of the OfferWhereInput seen here?

input OfferWhereInput
{
  AND: [OfferWhereInput!]
  OR: [OfferWhereInput!]
  NOT: OfferWhereInput
  vendor: VendorFieldInput
}

So if you want to match with multiple DateCriterion you put them in the AND? And also, in the root OfferWhereInput, can multiple fields be used at the same time? What will that result in? And more importantly, why is even OR and NOT defined? They are not included in any of the query-templates. @hartig  @chengsijin0817

**Comment by chengsijin0817** [comment]
Currently, if we want to match with multiple conditions, we have 3 options: root OfferWhereInput level, 'AND' level, and field level like 'comment':
* In the root OfferWhereinput, multiple fields can be used at the same time. In one array, relations of multiple conditions is regarded as 'OR' default.
* Comment and publishDate level: if two conditions share the same field, the following query is also acceptable
```
{
	Producer(nr:$producerID) {
		product {
			offers(where:{
			vendor:{comment:[{criterion:START_with, pattern:$commentOfVendorkeyword1}, {criterion:END_with, pattern:$commentOfVendorkeyword2}]}
			}){	
				price
				offerWebpage
				product {label comments}
			}
		}
	}
}
```

However, to control 'multiple conditions' more simply and clearly, I will modify it and only put in the 'AND' level.

// OR and NOT:
Though we don't use OR and NOT in our query-templates, we still want to supply these parallel options, for some potential queries or usage.

**Comment by chengsijin0817** [comment]
Please find the newest version in the Google doc. If you have any questions when implementing. Please feel free to create/comment issues here.
Thanks.:-D

**Comment by ljukas** [comment]
Is there any special reason why you want to support different ways of matching with multiple conditions? It does not really offer anything except making the schema more complex and revolvers harder to write? 

This would be a clearer way of writing the same query as you wrote above:
```
...
offers(where:{
          AND: [vendor:{ comment: { criterion:START_with, pattern:$commentOfVendorkeyword1}}, 
                    vendor:{ comment: { criterion:END_with, pattern:$commentOfVendorkeyword2}}]
          }) 
...
```

It also has some questions:
1. If you have multiple comment-matchers as in your example, are they AND or ORs? (they are not in an AND- or OR-block, so we cannot know from just looking)
2. If inside an OR-block and we have multiple comment-matchers as in your example, are they AND or ORs?

If you skip being able to use multiple conditions inside comment and publishdate this confusion is non-existent, everything in the AND will be AND, everything in an OR is OR. 

Having multiple OfferWhereInput also seems unnecessary but is more understandable.

**Comment by ljukas** [comment]
Kind of related, but these:
```
Type AndExp{
  AND: [OfferWhereInput]
}
Type OrExp{
  OR: [OfferWhereInput]
}
Type NotExp{
  NOT: [OfferWhereInput]
}
Type FieldExp{
  Vendor: VendorFieldInput
}

```
Should probably be "input" and not "type". :D Also, weren't NOT supposed to not be an array?

**Comment by chengsijin0817** [comment]
My initial idea of supporting different matching level is trying to avoid repeating the same field several times in conditions, as you see in the example query. But it's not a big problem, if it makes the implementation more complex, let's remove it.
Anyway, now everything is in the 'AND',  'OR' level. Also, changed from object type to input type.
Please find it in the Google doc.

**Comment by hartig** [comment]
I am re-opening this issue again because there are still some issues left.

First of all, the schema now contains the following line.
```graphql
union OfferWhereInput = AndExp|OrExp|NotExp|FieldExp
```
I don't think that a union type can be used as an input type. Can someone please check.

**Comment by ljukas** [comment]
> Also the above solution won't work since you cannot use "union" on inputs, so we cant have an input that is a union.

I wrote this earlier, but yes you are correct. You cannot use union for Inputs. I am therefore using the following in my implementation:

`  input OfferWhereInput {
    AND: [OfferWhereInput!]
    NOT: OfferWhereInput
    OR: [OfferWhereInput]
    vendor: VendorFieldInput
  }
`

**Comment by hartig** [comment]
Another issue: I agree with Lukas, if we do not use OR and NOT in our query templates, then we should remove them from the schema.

In general, we should be consistent regarding all the additional stuff we add to the schema. Our rule should be: only add exactly the features that are used in at least one of our query templates.

**Comment by hartig** [comment]
Lukas, I would like you to implement our schema, exactly how it is defined. If there is an issue with the definition, then the definition has to be changed, not the other way around.

Sijin, please implement the change (both in the schema and in the corresponding query templates). Thereafter, please indicate here which query templates have been affected.

**Comment by chengsijin0817** [comment]
Lukas, sorry I didn't notice that you edited the comment yesterday, so that I missed the important message that 'union' can't be used as inputs. Sorry about that.

Olaf, thanks. I have modified the 'OfferWhereInput' to the previous format, and also removed 'NOT' 'OR' field. 'OfferWhereInput' is shown as following, no query template is affected by this modification:

 input OfferWhereInput
{
  AND: [OfferWhereInput!]
  vendor: VendorFieldInput
}

**Comment by hartig** [comment]
Why is there no no query template that is affected by this modification?
Is it because the previous version of this part of the schema was syntactically the same in terms of the queries?

**Comment by ljukas** [comment]
What change are you talking about?

**Comment by chengsijin0817** [comment]
@hartig , yeah, they are syntactically the same in terms of queries.
The trouble is that 'union' can't be used as input.

@ljukas I think Olaf is talking about the following two versions of 'OfferWhereInput'. Currently, I think the issue has been fixed because we have reached an agreement in terms of design and implementation.
1. The first version:
input OfferWhereInput
{
AND: [OfferWhereInput!]
OR: [OfferWhereInput!]
NOT: OfferWhereInput
vendor: VendorFieldInput
}
2. The second version:
union AndExp|OrExp|NotExp|FieldExp
input AndExp{
  AND: [OfferWhereInput!]
}
input OrExp{
  OR: [OfferWhereInput!]
}
input NotExp{
  NOT: OfferWhereInput
}
input FieldExp{
  Vendor: VendorFieldInput
}

**Comment by hartig** [comment]
Lukas, I was talking about the change to define `OfferWhereInput` as an *input* type of the following form.
```graphql
input OfferWhereInput {
  AND: [OfferWhereInput!]
  vendor: VendorFieldInput
}
```
Okay?

In the meantime, Sijin has implemented this change. So, Lukas, can you please check again the current version of the schema and confirm a) that you are okay with it and b) that this is exactly what you are implementing.

**Comment by ljukas** [comment]
That works for me, I just have to remove some code but that is really not an issue.

**Comment by hartig** [comment]
Lukas, thanks for the confirmation.

Great, then we are done here. I will close this issue.
