### ISSUE TITLE
OrderFieldInput - Q8

### ISSUE THREAD

**Issue by ljukas** [LiUGraphQL/LinGBM#32]
I just want to ask how this is supposed to work.

In the following query:

`offers(where: OfferWhereInput, limit: Int, order: [OrderFieldInput]): [Offer]`

We can give an order argument which is a list of OrderFieldInputs, each OrderFieldInputs can have two fields to order by. 

If there is just ONE OrderFieldInput my guess would be that we sort first after the orderField1, and secondly we sort by orderField2, but we keep the order given in orderField1. 

My question then is how should it work if there is a list of OrderFieldInputs? Q8 uses this input, but it says that $attrOffer1 is selected from the 10 possible values of OffersSortingField, the same for $attrOffer2. But the schema does not match here.

The query template should look like the following to use the current schema:
```
{
  offers(limit:$cnt, order: { orderField1: $attrOffer1, orderField2: $attrOffer2} ) {
    offerWebpage
    validFrom
    price
}
```

Notice here that it does not take an Array, but a singel OrderFieldInput.

We need to decide here which approach to take. I recommend taking the example given above. That the order argument is always just a single OrderFieldInput, and we can therefore sort by 2 fields as a maximum.

**Comment by hartig** [comment]
Thanks for spotting this issue!!

Why do you recommend the approach of using the `OrderFieldInput` type as it is currently defined (with two fields, `orderField1` and `orderField2`) instead of using an array of `OffersSortingField` values?
Note, I simply want to understand the rationale for your recommendation. To me, the array-based approach seems to be more logical because that's what people would probably use in practice (why artificially limit the number of ordering criteria?)

**Comment by ljukas** [comment]
I actually didnt think of the approach of an array of OffersSortingField. That would probably be the best approach. The array approach that I was confused to would be the one with an array of OrderFieldInput as the schema says.

**Comment by hartig** [comment]
I see. Of course, an array of OrderFieldInput does not make sense. So, let's change it to an array of OffersSortingField elements.

Sijin, can you please implement the change, both in the schema and in the corresponding query templates.

**Comment by chengsijin0817** [comment]
Fixed.

**Comment by hartig** [comment]
Sijin, thanks for implementing the change. I am closing this issue now.
