### ISSUE TITLE
Q10 - Schema 

### ISSUE THREAD

**Issue by ljukas** [LiUGraphQL/LinGBM#34]
Q10 looks like the following:

```
query stringMatching($textOfReviewKeyword:String)
{
  reviewSearch(field:text,
               criterion:contains,
               pattern:$textOfReviewKeyword)
  
    title 
    label
  
}
```

reviewSearch returns a list of reviews according to the schema:

`reviewSearch(field: ReviewFieldInput!, criterion: StringCriterion!, pattern: String!): [Review]`

A Review has no field label, like the query template want us to return. Propose to remove that field, or change it to one that exists.

**Comment by chengsijin0817** [comment]
Thank, how about changing the field 'label' to 'text'?
If it's fine, I will change it in the query template file.

**Comment by hartig** [comment]
Yes, changing `label` to `text` in the query template is fine. I see that you have already implemented this change.

Lukas, to indicate that you are also happy with it please close this issue.
