### ISSUE TITLE
QueryGen Errors

### ISSUE THREAD

**Issue by ljukas** [LiUGraphQL/LinGBM#35]
I've started work on a preliminary test-driver. It runs all queries in the actualQueries folder synchrounously.

When I send the following query:
```
{
  reviewSearch(field:text,
               criterion:contains,
               pattern:"elms")
  {
    title 
    label
  }
}
```
I get an error on the criterion field, because according to the schema it is a StringCriterion:

```
enum StringCriterion 
{
    CONTAINS
    START_with
    END_with
    EQUALS  
}
```
Which is all caps. So the querygen needs to be modified to fit the schema. I also recommend changing the START_with to START_WITH and the same for END_with. 

NOTE: Its the queryTemplate10.txt that needs to be edited.

Regarding this, could I be allowed to push to branches on this repo? I have a fix for this issue on my machine but I cannot push it into a branch and make a pull-request. If I could do this I can fix issues and you just have to approve them instead of spending time on fixing them yourselves :smiley:

**Comment by chengsijin0817** [comment]
@ljukas Aha, yeah, I should modify the querygen to fit the schema also. Thanks.:-D
Sure, it's good if you can fix the issues and just make a pull request.

@hartig Hi, Olaf, could you please check Lukas' permission so that he could contribute to this repository? Thanks.

**Comment by hartig** [comment]
Lukas, nice catch. Thanks!

Of course, I can add you as a collaborator to this project. I actually wanted to do so earlier, but somehow I got sidetracked ;-)  Anyways, now I did.

So, whoever fixes the problem (via a pull request (PR) or just by a commit -- but preferably via a PR), can close this issue afterwards. Thanks!

**Comment by ljukas** [comment]
#36 Fixes most of the issues mentioned here. What is your thoughts on START_with -> START_WITH?

**Comment by hartig** [comment]
Thanks!

Regarding the renaming of START_with to START_WITH, I agree. Please do it.

**Comment by chengsijin0817** [comment]
Fixed
