### ISSUE TITLE
Heap Limit reached QT5

### ISSUE THREAD

**Issue by ljukas** [LiUGraphQL/LinGBM#44]
So... funny story...

This query:

```
{
  product(nr:405) {
    reviews {
      title
      reviewFor {
        reviews {
          title
          reviewFor {
            reviews {
              title
              reviewFor { 
                reviews {
                  text
                  title
                  reviewFor { label }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Because of the exponential growth of the returned object, the heap limit is reached on the server, and it crashes. 

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

Is that something we want to account for in testing? or would an alternative approach maybe be to remove the last "reviewFor" or similar? @hartig  @chengsijin0817

**Comment by ljukas** [comment]
When I remove the last "reviewFor" the server doesn't crash anymore and I get a response atleast. :)

**Comment by ljukas** [comment]
Just to add a little bit of info behind this.

The queryTemplate states that: 

> Thus, the query result trees consist of ca. 10,000 leaf nodes that all represent the same product, and the trees contain many duplicate internal nodes (not only within each level of depth but also across levels).

However, this specific product, 405, for me has 17 reviews. And because of the 4 times nesting we get:
17*17*17*17 = 83000:ish. And this is just the amount of reviews we get a the second bottom-most layer. We then also want to get the same product 83000 times. The amount of leaf-nodes here can therefore wildly vary from the estimated 10000 number.

And yes, with optimizations this query will be very, very fast, but the object that has to be returned will still be huge.

**Comment by ljukas** [comment]
I did a calculation of leaf nodes on an object returned when there were 15 reviews for a product. The amount of leaf nodes were then 155'490!! Thats 15x the estimation.

**Comment by ljukas** [comment]
So I think the crashes are happening because of the overhead for each call to the database. Which means the crashing-issue will disappear when caching/batching, mainly caching, is added to the server.

**Comment by hartig** [comment]
We are aware that the estimates for the result sizes can be quite far off, in particular for this query template. One of the things we want to do is to analyze the benchmark itself in order to achieve a better understanding of each of our query templates (e.g., what are their characteristics in terms of possible query instances, result sizes, different dataset sizes).

Now to your particular problem: I think it is not a problem if some queries cause issues for the most naive implementations. The test driver may use a timeout threshold and kill query instances that take longer than the threshold. Of course, these cases need to be recorded in the measurements files produced by the test driver.

**Comment by ljukas** [comment]
Alright, I see. Thanks for the answer.

Regarding your second paragraph it won't really help since it's the server that is crashing, and not the test-driver. And if the server crashes then the test-driver stops since the server is dead. So I have to figure out a way so that the server stops an query itself if it takes to long.

**Comment by hartig** [comment]
> So I have to figure out a way so that the server stops an query itself if it takes to long.

Either that or there is a way for the server to come back up again after a crash. But perhaps a server-side timeout is easier to implement. On the other hand, this may not always help; the heap limit may be reached before the timeout. However, do you have a rough idea about the time it takes before the out-of-memory error occurs on your server for that query?

**Comment by hartig** [comment]
Just for the record, Sijin and I are considering to change QT5 by removing one level of depth. Sijin is currently looking into the impact that such a change would have on the sizes of query results in benchmark datasets of different scale factors.

**Comment by ljukas** [comment]
Cool! I think that is a good change.

**Comment by chengsijin0817** [comment]
The QT5 with 3 cycles possesses similar characteristic with current QT5: results grow exponentially with depth, and the size of the result increases with the incremental of the scale factor, which is adequate to capture corresponding choke-points and do analysis.
Therefore, considering the crashing-issue, we decide to remove one level of depth on QT5.

**Comment by hartig** [comment]
@ljukas can you please check and confirm that the query instances of the new version of QT5 do not anymore cause the memory problems due to which you had opened this issue. Assuming that's the case, you can close this issue then.

**Comment by ljukas** [comment]
I've used the naive server to run over 700 different queries generated from QT5 without a crash. So I'd say it is fixed. Closing this issue.
