### ISSUE TITLE
QT13 Date-generation error

### ISSUE THREAD

**Issue by ljukas** [LiUGraphQL/LinGBM#46]
Hello.

This this bug is quite funny actually. The querygen gave me the following query:

```
{
  producer(nr:20) {
    products {
      offers(where:{ vendor:{ publishDate:{criterion:AFTER date:"2002-02-30"}}})
      {	
        price
        offerWebpage
        product {label comment}
      }
    }
  }
}
```

Can you spot the error?

Yes, the date doesn't exist, February does not have 30 days. :D Sending this query to the database causes it to send back an error because of "Incorrect DATE value".

**Comment by chengsijin0817** [comment]
Lukas, thanks for catching it. 
I will check the date error. (later today)

**Comment by chengsijin0817** [comment]
The date error has been fixed.
