### ISSUE TITLE
QT15 and QT16

### ISSUE THREAD

**Issue by ljukas** [LiUGraphQL/LinGBM#47]
Hello.

Short question and your thoughts around it.

So since the querygen does not generate any query which has the same arguments as any other, some of the queryTemplates are hard to generate in big numbers. 

For example when I run the querygen with "-nm 200" I still only get 12 queries each from these templates since thats how many vendors there are.

I suppose one way to increase the querygens limit is to generate a bigger database, which I think might be a good choice in my tests anyway.

But, maybe we should include an option that forces the querygen to generate the amount specified with the "-nm" flag? Or what do you think regarding this? @hartig @chengsijin0817 

A sample size of 12 is not good for much right?

**Comment by hartig** [comment]
> I suppose one way to increase the querygens limit is to generate a bigger database

Correct.

> But, maybe we should include an option that forces the querygen to generate the amount specified with the "-nm" flag?

Yes. There could be an additional "--duplicates-allowed" flag.

> A sample size of 12 is not good for much right?

That depends on what you want to measure. If you want to measure average query execution time across the queries per query template, then 12 is okay. Same for average result size across the queries per query template.
On the other hand, if you want to measure some form of throughput (number of queries per hour or, at least, per minute), then 12 may not be sufficient---in particular not if you are doing this with multiple clients that are supposed to have disjoint workloads. However, for such throughput-related experiments you may relax the disjointness/no-duplicate requirement. Then, the test driver may simply take care of starting again from the first query once the last query has been reached but the measurement period (i.e., the aforementioned hour, or minute) is not over yet.

**Comment by hartig** [comment]
Lukas, can we close this issue?
(if yes, please do so)

**Comment by ljukas** [comment]
We don't have a "duplicates allowed flag", but I think  we can close this issue, yes.
