### ISSUE TITLE
directories and file names of query templates

### ISSUE THREAD

**Issue by hartig** [LiUGraphQL/LinGBM#48]
@chengsijin0817 After seeing the new directory/file structure with the query templates now, I realize that I would like this to be slightly different still.

First, I think that the individual files for the query templates and their "description" should *not* be in separate sub-directories. Instead, these files should all be under `./artifacts/queryTemplates/main/`

Second, the files should be renamed:
* The files with the query templates should be named QT1.txt, QT2.txt, etc.
* The files with the variable names should be named QT1.vars, QT2.vars, etc.

/cc @ljukas

**Comment by chengsijin0817** [comment]
Thanks, I have restructured the directory, renamed the files and updated the 'querygen' program accordingly. 
Please check it.

**Comment by hartig** [comment]
Thanks Sijin! I am closing this issue now.

Lukas, note that this change may also have an effect on your test driver.
