### ISSUE TITLE
Schema - Person

### ISSUE THREAD

**Issue by ljukas** [LiUGraphQL/LinGBM#50]
So, I found now that the Person type in the schema is not used in any of the query-templates. So maybe we should remove it from the schema?

**Comment by ljukas** [comment]
Nevermind...

**Comment by hartig** [comment]
Just for the sake of documentation: I guess the reason why this issue was closed ("nevermind") is that @ljukas figured that the Person type is used in all query templates that have something to do with reviewers.

**Comment by ljukas** [comment]
Yes, sorry. Persons are never used explicitly, but instead renamed to reviewer. Missed that when I was looking for it in the resolvers.

**Comment by hartig** [comment]
No problem. I just wanted to make sure that none who sees this issue gets confused about why you closed it without any explanation ;-)
