### ISSUE TITLE
Error: Unknown type "publicationField".

### ISSUE THREAD

**Issue by rjkhan** [LiUGraphQL/LinGBM#61]
In type Query 
`publicationSearch(field: publicationField!, criterion: StringCriterion!, pattern: String!): [Publication]`
this should be replaced by this i think.

`publicationSearch(field: PublicationField!, criterion: StringCriterion!, pattern: String!): [Publication]`

**Comment by chengsijin0817** [comment]
Yes, please do it. Thanks.
