### ISSUE TITLE
issue Query template q12.txt

### ISSUE THREAD

**Issue by rjkhan** [LiUGraphQL/LinGBM#64]
```
query subqueryFilter1($universityID:ID, $departmentID:ID) 
{ 
  university(nr:$universityID) { 
    doctoralDegreeObtainers (where: {department: {nr:$departmentID} } ){ 
      id 
      emailAddress 
      publications {id } 
    } 
  } 
} 

```

this should be replaced by this 

`query subqueryFilter1($universityID:ID, $departmentID:ID) 
{ 
  university(nr:$universityID) { 
    doctoralDegreeObtainers (where: {worksFor :  { nr: $departmentID} } ){ 
      id 
      emailAddress 
      publications {id } 
    } 
  } 
} 
`

in doctoralDegreeObtainers instead of the department, we have workFor as input parameter in the schema

**Comment by chengsijin0817** [comment]
Thanks, fixed
