### ISSUE TITLE
Issue in query Template q14.txt

### ISSUE THREAD

**Issue by rjkhan** [LiUGraphQL/LinGBM#65]
`query multipleFilters($departmentID:ID,$professorType:String, $interestkeyword:String) 
{ 
  university(nr:$universityID) { 
    undergraduateDegreeObtainedBystudent(where: {AND:[{advisor:{age:{criterion:MORETHAN, pattern:$age}}},{advisor:{researchInterest:{criterion:CONTAINS, pattern:$interestKeyword}}}]}) { 
      id 
      emailAddress 
      takeGraduateCourses {id} 
    } 
  } 
}`

in the filter field, there is unknown parameter advisor: **age**

i think possible correct query structure is 

`query multipleFilters(
  $departmentID: ID
  $professorType: String
  $interestkeyword: String
) {
  university(nr: $universityID) {
    undergraduateDegreeObtainedBystudent(
      where: {
        AND: {
          age: { pattern: $interestkeyword, criterion: MORETHAN }
          advisor: {
            researchInterest: { criterion: CONTAINS, pattern: $interestkeyword }
          }
        }
      }
    ) {
      id
      emailAddress
      takeGraduateCourses {
        id
      }
    }
  }
}`
calling  *and filter with this* `AND:{}`   **not with this** `AND:[]`

**Comment by chengsijin0817** [comment]
Thanks
