### ISSUE TITLE
issue Query template QT4.txt

### ISSUE THREAD

**Issue by rjkhan** [LiUGraphQL/LinGBM#70]
`query lecturer_university_graduateStudent_professor_department($lecturerID:ID) 
{ 
  lecturer(nr:$lecturerID) { 
    doctoralDegreeFrom { 
      id 
      undergraduateDegreeObtainedBystudent { 
        id 
        email 
        advisor { 
          id 
          emailAddress  
          worksFor {id} 
        } 
      } 
    } 
  } 
} `

There is issue **email** should be replaced with **emailAddress** in above query template and it looks like this

`query lecturer_university_graduateStudent_professor_department($lecturerID:ID) 
{ 
  lecturer(nr:$lecturerID) { 
    doctoralDegreeFrom { 
      id 
      undergraduateDegreeObtainedBystudent { 
        id 
        emailAddress 
        advisor { 
          id 
          emailAddress  
          worksFor {id} 
        } 
      } 
    } 
  } 
} `

**Comment by chengsijin0817** [comment]
Thanks. This issue has been fixed in the commit: ce8c0b2448814bbfecd108554dffb4742c02268e
