### ISSUE TITLE
Better checking of arguments in the query generator

### ISSUE THREAD

**Issue by hartig** [LiUGraphQL/LinGBM#93]
The query generator should check whether the given arguments can actually be used.

For instance, in line 115 of generator.java, check that the given `queryTemplateDir` refers to an existing directory and that this is indeed a directory. If that's not the case, then `dir.listFiles()` in line 118 may return `null` and there will be an error in line 119.

**Comment by chengsijin0817** [comment]
Fixed. Please check commit ec32294
